- name: Instalar programas de ofimática
  hosts: all
  become: yes
  tags: ofimatica

  tasks:
  - name: Actualizar la lista de paquetes
    apt:
      update_cache: yes

  - name: Instalar GnuCash
    apt:
      name: gnucash
      state: present

  - name: Instalar Scribus
    apt:
      name: scribus
      state: present

  - name: Instalar Calibre
    apt:
      name: calibre
      state: present
